### ISSUE TITLE
NPM update broke existing install

### ISSUE THREAD

**Issue by edifirut** [openline-ai/openline-cli#68]
i had openline package installed ( openline/0.3.11 )

i've ran the update command
`sudo npm update -g openline`

and the output was:

Password:
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

removed 202 packages, and audited 204 packages in 1s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
efirut@Firuts-MacBook-Pro work % openline --help
zsh: command not found: openline

To put it back, i had to reinstall it again: npm install -g openline

**Comment by mattbr0wn** [comment]
closing as NPM is deprecated
